apiVersion: v1
kind: Service
metadata:
  name: os-info-service
spec:
  type: NodePort
  selector:
    app: os-info
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007